# Generated by Django 5.2.15 on 2026-06-10 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '电影分类',
                'verbose_name_plural': '电影分类',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='片名')),
                ('description', models.TextField(verbose_name='剧情简介')),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='海报')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('actors', models.CharField(max_length=500, verbose_name='主演')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('duration', models.IntegerField(verbose_name='片长(分钟)')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ['-created_at'],
            },
        ),
    ]
