# Generated by Django 4.2.11 on 2026-06-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='项目名称')),
                ('principal_investigator', models.CharField(max_length=200, verbose_name='项目负责人')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('funding_source', models.CharField(blank=True, max_length=300, verbose_name='资助来源')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='经费(万元)')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('active', '进行中'), ('completed', '已完成'), ('suspended', '已暂停')], default='planning', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'db_table': 'research_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
