# Generated by Django 4.2.11 on 2026-06-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('authors', models.TextField(help_text='多个作者用逗号分隔', verbose_name='作者')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('keywords', models.CharField(blank=True, help_text='多个关键词用逗号分隔', max_length=500, verbose_name='关键词')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='发表日期')),
                ('source_journal', models.CharField(blank=True, max_length=300, verbose_name='来源期刊')),
                ('doi', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='DOI')),
                ('file', models.FileField(blank=True, null=True, upload_to='papers/%Y/%m/', verbose_name='文件')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'db_table': 'papers',
                'ordering': ['-created_at'],
            },
        ),
    ]
